### ISSUE TITLE
Hello, I noticed that your pre-training model does not include the dnd dataset. Are you using polyu, nam, sidd models directly?

### ISSUE THREAD

**Issue by lll143653** [caiyuanhao1998/PNGAN#12]

**Comment by caiyuanhao1998** [comment]
No, we have not released the DND models until now.

But we provide DND noise generation and removal results in the folder `results/DND/`

You can also check [the DND open leaderboard](https://noise.visinf.tu-darmstadt.de/benchmark/#results_srgb) to download our test results. Thanks.
