### ISSUE TITLE
Example to train PNGAN with new data

### ISSUE THREAD

**Issue by kwcckw** [caiyuanhao1998/PNGAN#8]
Hi,

Do you have any example to train PNGAN with new data? Right now i didn't see any related code in the repo and in case i overlooked it, could you point me to the correct section?

Thanks.

**Comment by caiyuanhao1998** [comment]
Hello, we have not released the training code so far. 
If you are interested, the following repo is a simple re-implementation of our work applied on Restormer.
Thanks.

**Comment by caiyuanhao1998** [comment]
https://github.com/GarrickZ2/Image-Denoising

**Comment by kwcckw** [comment]
Alright, thanks for the update.
