### ISSUE TITLE
Noising Generator

### ISSUE THREAD

**Issue by lkdci** [caiyuanhao1998/PNGAN#9]
Hi, thanks for the great work, is there any plans to share the Generator weights? I would like to use the pre-trained generated on create noisy images from my clean images data.

**Comment by caiyuanhao1998** [comment]
We have not released that part until now.

Yifan Yang and Zixuan Zhang reproduced our algorithm in [their repo](https://github.com/GarrickZ2/Image-Denoising)

They provided a PNGAN noise generation model.

I hope this will help you

**Comment by khronimo** [comment]
Is there any chance you could consider releasing the PNGAN noise generation weights? all of the model links in the GarrickZ2 / Image-Denoising repo you referenced are broken and there are open github issues on it dating back to 2022 about it that seem to be unresolved.
